name: Build and deploy ASP.Net Core app to Azure Web App - CommunityApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
          include-prerelease: true

      - name: Restore dependencies
        run: dotnet restore

      - name: List files in repository
        run: ls -alh
        
      - name: Check SQLite database file existence
        run: |
          echo "Listing files in the root directory:"
          ls -alh
          echo "Listing files in the publish directory:"
          ls -alh ${{env.DOTNET_ROOT}}/myapp

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Publish with dotnet
        run: dotnet publish --configuration Release --output ${{env.DOTNET_ROOT}}/myapp

      - name: Copy SQLite database
        run: |
          # Copy the SQLite database file to the publish directory
          cp ./localdatabase.db ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'CommunityApp'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_730765B90E2D470B9778505594F2FF2C }}
          package: .
